// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  CommandExecOutputDeltaNotification,
  CommandExecResizeParams,
  CommandExecResizeResponse,
  CommandExecTerminateParams,
  CommandExecTerminateResponse,
  CommandExecWriteParams,
  CommandExecWriteResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const commandExecWritePublicRequest = {
  "id": "write-public-1",
  "method": "command/exec/write",
  "params": {
    "processId": "command-1",
    "deltaBase64": "aGVsbG8K",
    "closeStdin": true
  }
} satisfies BoundRequest<"command/exec/write">;
export const commandExecWritePublicRequestParams = commandExecWritePublicRequest.params satisfies CommandExecWriteParams;

export const commandExecWritePublicNullRequest = {
  "id": "write-public-null-1",
  "method": "command/exec/write",
  "params": {
    "processId": "command-1",
    "deltaBase64": null,
    "closeStdin": false
  }
} satisfies BoundRequest<"command/exec/write">;
export const commandExecWritePublicNullRequestParams = commandExecWritePublicNullRequest.params satisfies CommandExecWriteParams;

export const commandExecWriteLegacyRequest = {
  "id": "write-legacy-1",
  "method": "command/exec/write",
  "params": {
    "id": "command-1",
    "data": "hello\n",
    "encoding": "utf8",
    "close": true
  }
} satisfies BoundRequest<"command/exec/write">;
export const commandExecWriteLegacyRequestParams = commandExecWriteLegacyRequest.params satisfies CommandExecWriteParams;

export const commandExecWriteResponse = {
  "id": "write-public-1",
  "result": {
    "ok": true,
    "path": "command-1"
  }
} satisfies BoundResponse<"command/exec/write">;
export const commandExecWriteResponseResult = commandExecWriteResponse.result satisfies CommandExecWriteResponse;

export const commandExecResizePublicRequest = {
  "id": "resize-public-1",
  "method": "command/exec/resize",
  "params": {
    "processId": "command-1",
    "size": {
      "rows": 24,
      "cols": 80
    }
  }
} satisfies BoundRequest<"command/exec/resize">;
export const commandExecResizePublicRequestParams = commandExecResizePublicRequest.params satisfies CommandExecResizeParams;

export const commandExecResizeLegacyRequest = {
  "id": "resize-legacy-1",
  "method": "command/exec/resize",
  "params": {
    "id": "command-1",
    "rows": 24,
    "cols": 80
  }
} satisfies BoundRequest<"command/exec/resize">;
export const commandExecResizeLegacyRequestParams = commandExecResizeLegacyRequest.params satisfies CommandExecResizeParams;

export const commandExecResizeResponse = {
  "id": "resize-public-1",
  "result": {}
} satisfies BoundResponse<"command/exec/resize">;
export const commandExecResizeResponseResult = commandExecResizeResponse.result satisfies CommandExecResizeResponse;

export const commandExecTerminatePublicRequest = {
  "id": "terminate-public-1",
  "method": "command/exec/terminate",
  "params": {
    "processId": "command-1"
  }
} satisfies BoundRequest<"command/exec/terminate">;
export const commandExecTerminatePublicRequestParams = commandExecTerminatePublicRequest.params satisfies CommandExecTerminateParams;

export const commandExecTerminateLegacyRequest = {
  "id": "terminate-legacy-1",
  "method": "command/exec/terminate",
  "params": {
    "id": "command-1"
  }
} satisfies BoundRequest<"command/exec/terminate">;
export const commandExecTerminateLegacyRequestParams = commandExecTerminateLegacyRequest.params satisfies CommandExecTerminateParams;

export const commandExecTerminateResponse = {
  "id": "terminate-public-1",
  "result": {}
} satisfies BoundResponse<"command/exec/terminate">;
export const commandExecTerminateResponseResult = commandExecTerminateResponse.result satisfies CommandExecTerminateResponse;

export const commandExecOutputDeltaNotification = {
  "method": "command/exec/outputDelta",
  "params": {
    "processId": "command-1",
    "stream": "stdout",
    "deltaBase64": "aGVsbG8K",
    "capReached": false
  }
} satisfies BoundNotification<"command/exec/outputDelta">;
export const commandExecOutputDeltaNotificationParams = commandExecOutputDeltaNotification.params satisfies CommandExecOutputDeltaNotification;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
