// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  CommandExecutionApprovalRequestParams,
  CommandExecutionRequestApprovalResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const commandExecutionApprovalRequest = {
  "id": "approval-command-1",
  "method": "item/commandExecution/requestApproval",
  "params": {
    "threadId": "thread-1",
    "turnId": "turn-1",
    "itemId": "item-command-1",
    "startedAtMs": 1783715400000,
    "reason": "Approve process start",
    "command": "git status",
    "args": [
      "status"
    ],
    "cwd": ".",
    "operation": "start",
    "destructive": false,
    "availableDecisions": [
      "accept",
      "decline",
      "cancel"
    ]
  }
} satisfies BoundRequest<"item/commandExecution/requestApproval">;
export const commandExecutionApprovalRequestParams = commandExecutionApprovalRequest.params satisfies CommandExecutionApprovalRequestParams;

export const commandExecutionApprovalResponse = {
  "id": "approval-command-1",
  "result": {
    "decision": "accept"
  }
} satisfies BoundResponse<"item/commandExecution/requestApproval">;
export const commandExecutionApprovalResponseResult = commandExecutionApprovalResponse.result satisfies CommandExecutionRequestApprovalResponse;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
