// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  DynamicToolCallParams,
  DynamicToolCallResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const dynamicToolCallRequest = {
  "id": "interaction-1",
  "method": "item/tool/call",
  "params": {
    "threadId": "thread-1",
    "turnId": "turn-1",
    "callId": "call-1",
    "namespace": null,
    "tool": "client.search",
    "arguments": {
      "query": "gollem"
    },
    "requestId": "interaction-1",
    "itemId": "item-tool-1",
    "startedAtMs": 1783715400000,
    "toolName": "client.search",
    "name": "client.search",
    "metadata": {
      "source": "runtime"
    },
    "reason": "client.search"
  }
} satisfies BoundRequest<"item/tool/call">;
export const dynamicToolCallRequestParams = dynamicToolCallRequest.params satisfies DynamicToolCallParams;

export const dynamicToolCallTextResponse = {
  "id": "interaction-1",
  "result": {
    "contentItems": [
      {
        "type": "inputText",
        "text": "match"
      }
    ],
    "success": true
  }
} satisfies BoundResponse<"item/tool/call">;
export const dynamicToolCallTextResponseResult = dynamicToolCallTextResponse.result satisfies DynamicToolCallResponse;

export const dynamicToolCallImageResponse = {
  "id": "interaction-1",
  "result": {
    "contentItems": [
      {
        "type": "inputImage",
        "imageUrl": "data:image/png;base64,AA=="
      }
    ],
    "success": false
  }
} satisfies BoundResponse<"item/tool/call">;
export const dynamicToolCallImageResponseResult = dynamicToolCallImageResponse.result satisfies DynamicToolCallResponse;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
