// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  FileChangedNotification,
  FsChangedNotification,
  FsCopyParams,
  FsCopyResponse,
  FsCreateDirectoryParams,
  FsCreateDirectoryResponse,
  FsGetMetadataParams,
  FsGetMetadataResponse,
  FsReadDirectoryParams,
  FsReadDirectoryResponse,
  FsReadFileParams,
  FsReadFileResponse,
  FsRemoveParams,
  FsRemoveResponse,
  FsUnwatchParams,
  FsUnwatchResponse,
  FsWatchParams,
  FsWatchResponse,
  FsWriteFileParams,
  FsWriteFileResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const filesystemReadRequest = {
  "id": "read",
  "method": "fs/readFile",
  "params": {
    "path": "/workspace/file.bin"
  }
} satisfies BoundRequest<"fs/readFile">;
export const filesystemReadRequestParams = filesystemReadRequest.params satisfies FsReadFileParams;

export const filesystemReadResponse = {
  "id": "read",
  "result": {
    "dataBase64": "AAEC/w==",
    "path": "file.bin",
    "content": "AAEC/w==",
    "encoding": "base64",
    "size": 4,
    "mode": 420,
    "modTime": "2026-07-11T12:00:00Z",
    "contentTruncated": false
  }
} satisfies BoundResponse<"fs/readFile">;
export const filesystemReadResponseResult = filesystemReadResponse.result satisfies FsReadFileResponse;

export const filesystemWriteRequest = {
  "id": "write",
  "method": "fs/writeFile",
  "params": {
    "path": "/workspace/file.bin",
    "dataBase64": "AAEC/w=="
  }
} satisfies BoundRequest<"fs/writeFile">;
export const filesystemWriteRequestParams = filesystemWriteRequest.params satisfies FsWriteFileParams;

export const filesystemWriteResponse = {
  "id": "write",
  "result": {}
} satisfies BoundResponse<"fs/writeFile">;
export const filesystemWriteResponseResult = filesystemWriteResponse.result satisfies FsWriteFileResponse;

export const filesystemCreateDirectoryRequest = {
  "id": "mkdir",
  "method": "fs/createDirectory",
  "params": {
    "path": "/workspace/new/dir",
    "recursive": null
  }
} satisfies BoundRequest<"fs/createDirectory">;
export const filesystemCreateDirectoryRequestParams = filesystemCreateDirectoryRequest.params satisfies FsCreateDirectoryParams;

export const filesystemCreateDirectoryResponse = {
  "id": "mkdir",
  "result": {}
} satisfies BoundResponse<"fs/createDirectory">;
export const filesystemCreateDirectoryResponseResult = filesystemCreateDirectoryResponse.result satisfies FsCreateDirectoryResponse;

export const filesystemMetadataRequest = {
  "id": "metadata",
  "method": "fs/getMetadata",
  "params": {
    "path": "/workspace/file.bin"
  }
} satisfies BoundRequest<"fs/getMetadata">;
export const filesystemMetadataRequestParams = filesystemMetadataRequest.params satisfies FsGetMetadataParams;

export const filesystemMetadataResponse = {
  "id": "metadata",
  "result": {
    "isDirectory": false,
    "isFile": true,
    "isSymlink": false,
    "createdAtMs": 0,
    "modifiedAtMs": 1783771200000
  }
} satisfies BoundResponse<"fs/getMetadata">;
export const filesystemMetadataResponseResult = filesystemMetadataResponse.result satisfies FsGetMetadataResponse;

export const filesystemReadDirectoryRequest = {
  "id": "list",
  "method": "fs/readDirectory",
  "params": {
    "path": "/workspace"
  }
} satisfies BoundRequest<"fs/readDirectory">;
export const filesystemReadDirectoryRequestParams = filesystemReadDirectoryRequest.params satisfies FsReadDirectoryParams;

export const filesystemReadDirectoryResponse = {
  "id": "list",
  "result": {
    "entries": [
      {
        "fileName": "file.bin",
        "isDirectory": false,
        "isFile": true,
        "Path": "file.bin",
        "Name": "file.bin",
        "IsDir": false,
        "Size": 4,
        "Mode": 420,
        "ModTime": "2026-07-11T12:00:00Z"
      }
    ]
  }
} satisfies BoundResponse<"fs/readDirectory">;
export const filesystemReadDirectoryResponseResult = filesystemReadDirectoryResponse.result satisfies FsReadDirectoryResponse;

export const filesystemRemoveRequest = {
  "id": "remove",
  "method": "fs/remove",
  "params": {
    "path": "/workspace/file.bin",
    "recursive": false,
    "force": null
  }
} satisfies BoundRequest<"fs/remove">;
export const filesystemRemoveRequestParams = filesystemRemoveRequest.params satisfies FsRemoveParams;

export const filesystemRemoveResponse = {
  "id": "remove",
  "result": {}
} satisfies BoundResponse<"fs/remove">;
export const filesystemRemoveResponseResult = filesystemRemoveResponse.result satisfies FsRemoveResponse;

export const filesystemCopyRequest = {
  "id": "copy",
  "method": "fs/copy",
  "params": {
    "sourcePath": "/workspace/source",
    "destinationPath": "/workspace/destination",
    "recursive": true
  }
} satisfies BoundRequest<"fs/copy">;
export const filesystemCopyRequestParams = filesystemCopyRequest.params satisfies FsCopyParams;

export const filesystemCopyResponse = {
  "id": "copy",
  "result": {}
} satisfies BoundResponse<"fs/copy">;
export const filesystemCopyResponseResult = filesystemCopyResponse.result satisfies FsCopyResponse;

export const filesystemWatchRequest = {
  "id": "watch",
  "method": "fs/watch",
  "params": {
    "watchId": "watch-1",
    "path": "/workspace/file.bin"
  }
} satisfies BoundRequest<"fs/watch">;
export const filesystemWatchRequestParams = filesystemWatchRequest.params satisfies FsWatchParams;

export const filesystemWatchResponse = {
  "id": "watch",
  "result": {
    "path": "/workspace/file.bin"
  }
} satisfies BoundResponse<"fs/watch">;
export const filesystemWatchResponseResult = filesystemWatchResponse.result satisfies FsWatchResponse;

export const filesystemUnwatchRequest = {
  "id": "unwatch",
  "method": "fs/unwatch",
  "params": {
    "watchId": "watch-1"
  }
} satisfies BoundRequest<"fs/unwatch">;
export const filesystemUnwatchRequestParams = filesystemUnwatchRequest.params satisfies FsUnwatchParams;

export const filesystemUnwatchResponse = {
  "id": "unwatch",
  "result": {}
} satisfies BoundResponse<"fs/unwatch">;
export const filesystemUnwatchResponseResult = filesystemUnwatchResponse.result satisfies FsUnwatchResponse;

export const filesystemWatchChangedNotification = {
  "method": "fs/changed",
  "params": {
    "watchId": "watch-1",
    "changedPaths": [
      "/workspace/file.bin"
    ]
  }
} satisfies BoundNotification<"fs/changed">;
export const filesystemWatchChangedNotificationParams = filesystemWatchChangedNotification.params satisfies FsChangedNotification;

export const filesystemMutationChangedNotification = {
  "method": "fs/changed",
  "params": {
    "path": "file.bin",
    "operation": "writeFile",
    "at": "2026-07-11T12:00:00Z"
  }
} satisfies BoundNotification<"fs/changed">;
export const filesystemMutationChangedNotificationParams = filesystemMutationChangedNotification.params satisfies FileChangedNotification;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
// @ts-expect-error public writes require base64 data.
export const rejectFilesystemWriteWithoutData = { path: "/workspace/file" } satisfies FsWriteFileParams;
// @ts-expect-error copy recursive is non-null when present.
export const rejectFilesystemCopyNullRecursive = { sourcePath: "/workspace/a", destinationPath: "/workspace/b", recursive: null } satisfies FsCopyParams;
// @ts-expect-error directory responses require a non-null entries array.
export const rejectFilesystemNullEntries = { entries: null } satisfies FsReadDirectoryResponse;
// @ts-expect-error watch notifications require changedPaths.
export const rejectFilesystemChangedWithoutPaths = { watchId: "watch" } satisfies FsChangedNotification;
// @ts-expect-error metadata responses require every public field.
export const rejectFilesystemPartialMetadata = { isFile: true } satisfies FsGetMetadataResponse;
