// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  FileChangeItemCompletedNotificationParams,
  FileChangeItemStartedNotificationParams,
  FileChangePatchUpdatedNotification,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const fileChangeAddStarted = {
  "method": "item/started",
  "params": {
    "item": {
      "type": "fileChange",
      "id": "item-add",
      "changes": [
        {
          "path": "added.txt",
          "kind": {
            "type": "add"
          },
          "diff": "+added\n"
        }
      ],
      "status": "inProgress"
    },
    "threadId": "thread-1",
    "turnId": "turn-1",
    "startedAtMs": 1783715400000
  }
} satisfies BoundNotification<"item/started">;
export const fileChangeAddStartedParams = fileChangeAddStarted.params satisfies FileChangeItemStartedNotificationParams;

export const fileChangeDeleteCompleted = {
  "method": "item/completed",
  "params": {
    "item": {
      "type": "fileChange",
      "id": "item-delete",
      "changes": [
        {
          "path": "deleted.txt",
          "kind": {
            "type": "delete"
          },
          "diff": "-deleted\n"
        }
      ],
      "status": "completed"
    },
    "threadId": "thread-1",
    "turnId": "turn-1",
    "completedAtMs": 1783715400100
  }
} satisfies BoundNotification<"item/completed">;
export const fileChangeDeleteCompletedParams = fileChangeDeleteCompleted.params satisfies FileChangeItemCompletedNotificationParams;

export const fileChangePublicUpdateFailed = {
  "method": "item/completed",
  "params": {
    "item": {
      "type": "fileChange",
      "id": "item-update-public",
      "changes": [
        {
          "path": "updated.txt",
          "kind": {
            "type": "update",
            "move_path": null
          },
          "diff": "@@ -1 +1 @@\n-old\n+new\n"
        }
      ],
      "status": "failed"
    },
    "threadId": "thread-1",
    "turnId": "turn-1",
    "completedAtMs": 1783715400200
  }
} satisfies BoundNotification<"item/completed">;
export const fileChangePublicUpdateFailedParams = fileChangePublicUpdateFailed.params satisfies FileChangeItemCompletedNotificationParams;

export const fileChangeLegacyUpdateDeclined = {
  "method": "item/completed",
  "params": {
    "item": {
      "type": "fileChange",
      "id": "item-update-legacy",
      "changes": [
        {
          "path": "old-name.txt",
          "kind": {
            "type": "update",
            "movePath": "new-name.txt"
          },
          "diff": ""
        }
      ],
      "status": "declined"
    },
    "threadId": "thread-1",
    "turnId": "turn-1",
    "completedAtMs": 1783715400300
  }
} satisfies BoundNotification<"item/completed">;
export const fileChangeLegacyUpdateDeclinedParams = fileChangeLegacyUpdateDeclined.params satisfies FileChangeItemCompletedNotificationParams;

export const fileChangePatchUpdatedPublicPrecedence = {
  "method": "item/fileChange/patchUpdated",
  "params": {
    "threadId": "thread-1",
    "turnId": "turn-1",
    "itemId": "item-update-precedence",
    "changes": [
      {
        "path": "source.txt",
        "kind": {
          "type": "update",
          "move_path": "public-name.txt",
          "movePath": "legacy-name.txt"
        },
        "diff": ""
      }
    ]
  }
} satisfies BoundNotification<"item/fileChange/patchUpdated">;
export const fileChangePatchUpdatedPublicPrecedenceParams = fileChangePatchUpdatedPublicPrecedence.params satisfies FileChangePatchUpdatedNotification;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
