// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  InitializeParams,
  InitializeResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const initializeRequest = {
  "id": "initialize-1",
  "method": "initialize",
  "params": {
    "clientInfo": {
      "name": "gollem-typescript-fixture",
      "title": null,
      "version": "1.0.0"
    },
    "capabilities": {
      "experimentalApi": true,
      "requestAttestation": false,
      "mcpServerOpenaiFormElicitation": true,
      "optOutNotificationMethods": [
        "thread/tokenUsage/updated"
      ],
      "experimental": {
        "typedInitialize": true
      }
    }
  }
} satisfies BoundRequest<"initialize">;
export const initializeRequestParams = initializeRequest.params satisfies InitializeParams;

export const initializeResponse = {
  "id": "initialize-1",
  "result": {
    "userAgent": "gollem-appserver/dev",
    "codexHome": "/workspace/.gollem",
    "platformFamily": "unix",
    "platformOs": "macos",
    "protocolVersion": "gollem.appserver.v1",
    "serverInfo": {
      "name": "gollem-appserver",
      "version": "dev"
    },
    "capabilities": {
      "protocolSchema": true,
      "unavailable": true
    },
    "methods": [
      {
        "method": "initialize",
        "surface": "client-request",
        "state": "implemented"
      },
      {
        "method": "initialized",
        "surface": "client-notification",
        "state": "implemented"
      }
    ]
  }
} satisfies BoundResponse<"initialize">;
export const initializeResponseResult = initializeResponse.result satisfies InitializeResponse;

export const initializedNotification = {
  "method": "initialized"
} satisfies BoundNotification<"initialized">;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
// @ts-expect-error initialize requires clientInfo.
export const rejectInitializeWithoutClientInfo = { "capabilities": {} } satisfies InitializeParams;
// @ts-expect-error initialize requires clientInfo.version.
export const rejectInitializeWithoutClientVersion = { "clientInfo": { "name": "client" } } satisfies InitializeParams;
// @ts-expect-error initialized does not accept params.
export const rejectInitializedParams = { "method": "initialized", "params": {} } satisfies BoundNotification<"initialized">;
