// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  McpServerElicitationRequestParams,
  McpServerElicitationRequestResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const mcpElicitationFormRequest = {
  "id": "interaction-1",
  "method": "mcpServer/elicitation/request",
  "params": {
    "threadId": "thread-1",
    "turnId": "turn-1",
    "serverName": "repo",
    "mode": "form",
    "_meta": {
      "source": "runtime"
    },
    "message": "Choose access",
    "requestedSchema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "count": {
          "type": "integer",
          "minimum": 0,
          "maximum": 10
        },
        "enabled": {
          "type": "boolean",
          "default": true
        },
        "mode": {
          "type": "string",
          "oneOf": [
            {
              "const": "safe",
              "title": "Safe"
            },
            {
              "const": "fast",
              "title": "Fast"
            }
          ]
        },
        "scopes": {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "const": "read",
                "title": "Read"
              },
              {
                "const": "write",
                "title": "Write"
              }
            ]
          }
        }
      },
      "required": [
        "email",
        "enabled"
      ]
    },
    "requestId": "interaction-1",
    "itemId": "item-tool-1",
    "startedAtMs": 1783715400000,
    "serverId": "repo",
    "metadata": {
      "source": "runtime"
    },
    "reason": "Choose access"
  }
} satisfies BoundRequest<"mcpServer/elicitation/request">;
export const mcpElicitationFormRequestParams = mcpElicitationFormRequest.params satisfies McpServerElicitationRequestParams;

export const mcpElicitationOpenaiFormRequest = {
  "id": "interaction-2",
  "method": "mcpServer/elicitation/request",
  "params": {
    "threadId": "thread-1",
    "turnId": null,
    "serverName": "repo",
    "mode": "openai/form",
    "_meta": null,
    "message": "Complete the form",
    "requestedSchema": {
      "type": "vendor-form",
      "version": 1
    }
  }
} satisfies BoundRequest<"mcpServer/elicitation/request">;
export const mcpElicitationOpenaiFormRequestParams = mcpElicitationOpenaiFormRequest.params satisfies McpServerElicitationRequestParams;

export const mcpElicitationUrlRequest = {
  "id": "interaction-3",
  "method": "mcpServer/elicitation/request",
  "params": {
    "threadId": "thread-1",
    "turnId": null,
    "serverName": "repo",
    "mode": "url",
    "_meta": null,
    "message": "Open authorization",
    "url": "https://example.com/authorize",
    "elicitationId": "elicit-1"
  }
} satisfies BoundRequest<"mcpServer/elicitation/request">;
export const mcpElicitationUrlRequestParams = mcpElicitationUrlRequest.params satisfies McpServerElicitationRequestParams;

export const mcpElicitationResponse = {
  "id": "interaction-1",
  "result": {
    "action": "accept",
    "content": {
      "email": "safe@example.com",
      "enabled": true
    },
    "_meta": null
  }
} satisfies BoundResponse<"mcpServer/elicitation/request">;
export const mcpElicitationResponseResult = mcpElicitationResponse.result satisfies McpServerElicitationRequestResponse;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
