// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  ActivePermissionProfile,
  AdditionalPermissionProfile,
  FileSystemAccessMode,
  FileSystemPath,
  MethodResultsByName,
  PermissionGrantScope,
  PermissionsRequestApprovalParams,
  PermissionsRequestApprovalResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const permissionProfileRequest = {
  "threadId": "thread-1",
  "turnId": "turn-1",
  "itemId": "item-1",
  "environmentId": "local",
  "startedAtMs": 1783715400000,
  "cwd": "/workspace/project",
  "reason": "Grant network and workspace access",
  "permissions": {
    "network": {
      "enabled": true
    },
    "fileSystem": {
      "read": [
        "/workspace/project"
      ],
      "write": [
        "/workspace/project"
      ],
      "globScanMaxDepth": 3,
      "entries": [
        {
          "path": {
            "type": "special",
            "value": {
              "kind": "project_roots",
              "subpath": null
            }
          },
          "access": "write"
        },
        {
          "path": {
            "type": "glob_pattern",
            "pattern": "**/.env"
          },
          "access": "deny"
        }
      ]
    }
  }
} satisfies PermissionsRequestApprovalParams;

export const permissionProfileResponse = {
  "permissions": {
    "network": {
      "enabled": true
    },
    "fileSystem": {
      "read": null,
      "write": null,
      "entries": [
        {
          "path": {
            "type": "special",
            "value": {
              "kind": "project_roots",
              "subpath": null
            }
          },
          "access": "write"
        }
      ]
    }
  },
  "scope": "session",
  "strictAutoReview": false
} satisfies PermissionsRequestApprovalResponse;

export const activePermissionProfile = { id: ":workspace", extends: null } satisfies ActivePermissionProfile;
export const additionalPermissionProfile = { network: null, fileSystem: null } satisfies AdditionalPermissionProfile;

// @ts-expect-error filesystem access modes are closed.
export const rejectInvalidFilesystemAccess = "execute" satisfies FileSystemAccessMode;
// @ts-expect-error filesystem path variants cannot cross fields.
export const rejectCrossedFilesystemPath = { type: "path", pattern: "*.go" } satisfies FileSystemPath;
// @ts-expect-error permission grant scopes are closed.
export const rejectInvalidPermissionScope = "workspace" satisfies PermissionGrantScope;
// @ts-expect-error canonical permission requests require nullable environmentId.
export const rejectMissingPermissionEnvironment = { threadId: "t", turnId: "u", itemId: "i", startedAtMs: 1, cwd: "/workspace", reason: null, permissions: { network: null, fileSystem: null } } satisfies PermissionsRequestApprovalParams;
// @ts-expect-error canonical permission responses require scope.
export const rejectMissingPermissionScope = { permissions: {} } satisfies PermissionsRequestApprovalResponse;
// @ts-expect-error the incompatible live permission result remains unbound.
export type RejectPermissionResultBinding = MethodResultsByName["item/permissions/requestApproval"];
