// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  ThreadGoalClearParams,
  ThreadGoalClearResponse,
  ThreadGoalClearedNotification,
  ThreadGoalGetParams,
  ThreadGoalGetResponse,
  ThreadGoalSetParams,
  ThreadGoalSetResponse,
  ThreadGoalUpdatedNotification,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const threadGoalSetRequest = {
  "id": "goal-set-1",
  "method": "thread/goal/set",
  "params": {
    "threadId": "thread-1",
    "objective": "Finish the typed goal contract",
    "status": "active",
    "tokenBudget": 12000
  }
} satisfies BoundRequest<"thread/goal/set">;
export const threadGoalSetRequestParams = threadGoalSetRequest.params satisfies ThreadGoalSetParams;

export const threadGoalSetResponse = {
  "id": "goal-set-1",
  "result": {
    "goal": {
      "threadId": "thread-1",
      "objective": "Finish the typed goal contract",
      "status": "active",
      "tokenBudget": 12000,
      "tokensUsed": 320,
      "timeUsedSeconds": 45,
      "createdAt": 1783715400,
      "updatedAt": 1783715445
    }
  }
} satisfies BoundResponse<"thread/goal/set">;
export const threadGoalSetResponseResult = threadGoalSetResponse.result satisfies ThreadGoalSetResponse;

export const threadGoalSetLegacyIdRequest = {
  "id": "goal-set-legacy-1",
  "method": "thread/goal/set",
  "params": {
    "id": "thread-1",
    "goal": "Legacy objective"
  }
} satisfies BoundRequest<"thread/goal/set">;
export const threadGoalSetLegacyIdRequestParams = threadGoalSetLegacyIdRequest.params satisfies ThreadGoalSetParams;

export const threadGoalGetRequest = {
  "id": "goal-get-1",
  "method": "thread/goal/get",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundRequest<"thread/goal/get">;
export const threadGoalGetRequestParams = threadGoalGetRequest.params satisfies ThreadGoalGetParams;

export const threadGoalGetResponse = {
  "id": "goal-get-1",
  "result": {
    "goal": null
  }
} satisfies BoundResponse<"thread/goal/get">;
export const threadGoalGetResponseResult = threadGoalGetResponse.result satisfies ThreadGoalGetResponse;

export const threadGoalGetLegacyIdRequest = {
  "id": "goal-get-legacy-1",
  "method": "thread/goal/get",
  "params": {
    "id": "thread-1"
  }
} satisfies BoundRequest<"thread/goal/get">;
export const threadGoalGetLegacyIdRequestParams = threadGoalGetLegacyIdRequest.params satisfies ThreadGoalGetParams;

export const threadGoalClearRequest = {
  "id": "goal-clear-1",
  "method": "thread/goal/clear",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundRequest<"thread/goal/clear">;
export const threadGoalClearRequestParams = threadGoalClearRequest.params satisfies ThreadGoalClearParams;

export const threadGoalClearResponse = {
  "id": "goal-clear-1",
  "result": {
    "cleared": true
  }
} satisfies BoundResponse<"thread/goal/clear">;
export const threadGoalClearResponseResult = threadGoalClearResponse.result satisfies ThreadGoalClearResponse;

export const threadGoalClearLegacyIdRequest = {
  "id": "goal-clear-legacy-1",
  "method": "thread/goal/clear",
  "params": {
    "id": "thread-1"
  }
} satisfies BoundRequest<"thread/goal/clear">;
export const threadGoalClearLegacyIdRequestParams = threadGoalClearLegacyIdRequest.params satisfies ThreadGoalClearParams;

export const threadGoalUpdatedNotification = {
  "method": "thread/goal/updated",
  "params": {
    "threadId": "thread-1",
    "turnId": null,
    "goal": {
      "threadId": "thread-1",
      "objective": "Finish the typed goal contract",
      "status": "blocked",
      "tokenBudget": null,
      "tokensUsed": 640,
      "timeUsedSeconds": 90,
      "createdAt": 1783715400,
      "updatedAt": 1783715490
    }
  }
} satisfies BoundNotification<"thread/goal/updated">;
export const threadGoalUpdatedNotificationParams = threadGoalUpdatedNotification.params satisfies ThreadGoalUpdatedNotification;

export const threadGoalClearedNotification = {
  "method": "thread/goal/cleared",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundNotification<"thread/goal/cleared">;
export const threadGoalClearedNotificationParams = threadGoalClearedNotification.params satisfies ThreadGoalClearedNotification;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
