// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  ThreadArchiveParams,
  ThreadArchiveResponse,
  ThreadDeleteParams,
  ThreadDeleteResponse,
  ThreadLoadedListParams,
  ThreadLoadedListResponse,
  ThreadSetNameParams,
  ThreadSetNameResponse,
  ThreadUnarchiveParams,
  ThreadUnarchiveResponse,
  ThreadUnsubscribeParams,
  ThreadUnsubscribeResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const threadLoadedListRequest = {
  "id": "loaded-list-1",
  "method": "thread/loaded/list",
  "params": {
    "cursor": "0",
    "limit": 20
  }
} satisfies BoundRequest<"thread/loaded/list">;
export const threadLoadedListRequestParams = threadLoadedListRequest.params satisfies ThreadLoadedListParams;

export const threadLoadedListResponse = {
  "id": "loaded-list-1",
  "result": {
    "data": [
      "thread-1"
    ],
    "nextCursor": null
  }
} satisfies BoundResponse<"thread/loaded/list">;
export const threadLoadedListResponseResult = threadLoadedListResponse.result satisfies ThreadLoadedListResponse;

export const threadArchiveRequest = {
  "id": "archive-1",
  "method": "thread/archive",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundRequest<"thread/archive">;
export const threadArchiveRequestParams = threadArchiveRequest.params satisfies ThreadArchiveParams;

export const threadArchiveResponse = {
  "id": "archive-1",
  "result": {}
} satisfies BoundResponse<"thread/archive">;
export const threadArchiveResponseResult = threadArchiveResponse.result satisfies ThreadArchiveResponse;

export const threadUnarchiveRequest = {
  "id": "unarchive-1",
  "method": "thread/unarchive",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundRequest<"thread/unarchive">;
export const threadUnarchiveRequestParams = threadUnarchiveRequest.params satisfies ThreadUnarchiveParams;

export const threadUnarchiveResponse = {
  "id": "unarchive-1",
  "result": {
    "thread": {
      "id": "thread-1",
      "title": "Lifecycle",
      "workspace": "/workspace",
      "status": "active",
      "createdAt": "2026-07-10T20:30:00Z",
      "updatedAt": "2026-07-10T20:35:00Z"
    }
  }
} satisfies BoundResponse<"thread/unarchive">;
export const threadUnarchiveResponseResult = threadUnarchiveResponse.result satisfies ThreadUnarchiveResponse;

export const threadDeleteRequest = {
  "id": "delete-1",
  "method": "thread/delete",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundRequest<"thread/delete">;
export const threadDeleteRequestParams = threadDeleteRequest.params satisfies ThreadDeleteParams;

export const threadDeleteResponse = {
  "id": "delete-1",
  "result": {}
} satisfies BoundResponse<"thread/delete">;
export const threadDeleteResponseResult = threadDeleteResponse.result satisfies ThreadDeleteResponse;

export const threadUnsubscribeRequest = {
  "id": "unsubscribe-1",
  "method": "thread/unsubscribe",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundRequest<"thread/unsubscribe">;
export const threadUnsubscribeRequestParams = threadUnsubscribeRequest.params satisfies ThreadUnsubscribeParams;

export const threadUnsubscribeResponse = {
  "id": "unsubscribe-1",
  "result": {
    "status": "unsubscribed"
  }
} satisfies BoundResponse<"thread/unsubscribe">;
export const threadUnsubscribeResponseResult = threadUnsubscribeResponse.result satisfies ThreadUnsubscribeResponse;

export const threadSetNameRequest = {
  "id": "set-name-1",
  "method": "thread/name/set",
  "params": {
    "threadId": "thread-1",
    "name": "Renamed thread"
  }
} satisfies BoundRequest<"thread/name/set">;
export const threadSetNameRequestParams = threadSetNameRequest.params satisfies ThreadSetNameParams;

export const threadSetNameResponse = {
  "id": "set-name-1",
  "result": {}
} satisfies BoundResponse<"thread/name/set">;
export const threadSetNameResponseResult = threadSetNameResponse.result satisfies ThreadSetNameResponse;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
