// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  ThreadArchivedNotification,
  ThreadClosedNotification,
  ThreadDeletedNotification,
  ThreadUnarchivedNotification,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const threadArchivedNotification = {
  "method": "thread/archived",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundNotification<"thread/archived">;
export const threadArchivedNotificationParams = threadArchivedNotification.params satisfies ThreadArchivedNotification;

export const threadClosedNotification = {
  "method": "thread/closed",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundNotification<"thread/closed">;
export const threadClosedNotificationParams = threadClosedNotification.params satisfies ThreadClosedNotification;

export const threadDeletedNotification = {
  "method": "thread/deleted",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundNotification<"thread/deleted">;
export const threadDeletedNotificationParams = threadDeletedNotification.params satisfies ThreadDeletedNotification;

export const threadUnarchivedNotification = {
  "method": "thread/unarchived",
  "params": {
    "threadId": "thread-1"
  }
} satisfies BoundNotification<"thread/unarchived">;
export const threadUnarchivedNotificationParams = threadUnarchivedNotification.params satisfies ThreadUnarchivedNotification;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
