// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  ThreadListParams,
  ThreadListResponse,
  ThreadReadParams,
  ThreadReadResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const threadListRequest = {
  "id": "thread-list-1",
  "method": "thread/list",
  "params": {
    "cursor": "0",
    "limit": 20,
    "sortKey": "updated_at",
    "sortDirection": "desc",
    "modelProviders": [
      "openai"
    ],
    "sourceKinds": [
      "appServer"
    ],
    "archived": false,
    "cwd": [
      "/workspace/a",
      "/workspace/b"
    ],
    "useStateDbOnly": true,
    "searchTerm": "typed protocol",
    "statuses": [
      "active"
    ],
    "includeDeleted": false
  }
} satisfies BoundRequest<"thread/list">;
export const threadListRequestParams = threadListRequest.params satisfies ThreadListParams;

export const threadListResponse = {
  "id": "thread-list-1",
  "result": {
    "data": [
      {
        "id": "thread-1",
        "title": "Typed protocol",
        "workspace": "/workspace/a",
        "status": "active",
        "settings": {
          "providerId": "openai"
        },
        "metadata": {
          "sourceKind": "appServer"
        },
        "createdAt": "2026-07-10T20:30:00Z",
        "updatedAt": "2026-07-10T20:35:00Z"
      }
    ],
    "nextCursor": null,
    "backwardsCursor": "0",
    "threads": [
      {
        "id": "thread-1",
        "title": "Typed protocol",
        "workspace": "/workspace/a",
        "status": "active",
        "settings": {
          "providerId": "openai"
        },
        "metadata": {
          "sourceKind": "appServer"
        },
        "createdAt": "2026-07-10T20:30:00Z",
        "updatedAt": "2026-07-10T20:35:00Z"
      }
    ]
  }
} satisfies BoundResponse<"thread/list">;
export const threadListResponseResult = threadListResponse.result satisfies ThreadListResponse;

export const threadReadRequest = {
  "id": "thread-read-1",
  "method": "thread/read",
  "params": {
    "threadId": "thread-1",
    "includeTurns": true,
    "includeItems": true,
    "afterSeq": 0,
    "limit": 100
  }
} satisfies BoundRequest<"thread/read">;
export const threadReadRequestParams = threadReadRequest.params satisfies ThreadReadParams;

export const threadReadResponse = {
  "id": "thread-read-1",
  "result": {
    "thread": {
      "id": "thread-1",
      "title": "Typed protocol",
      "workspace": "/workspace/a",
      "status": "active",
      "createdAt": "2026-07-10T20:30:00Z",
      "updatedAt": "2026-07-10T20:35:00Z",
      "turns": [
        {
          "id": "turn-1",
          "threadId": "thread-1",
          "status": "completed",
          "input": {
            "prompt": "hello"
          },
          "createdAt": "2026-07-10T20:31:00Z",
          "updatedAt": "2026-07-10T20:32:00Z",
          "items": [
            {
              "id": "item-1",
              "threadId": "thread-1",
              "turnId": "turn-1",
              "seq": 1,
              "kind": "message",
              "status": "completed",
              "payload": {
                "role": "user",
                "text": "hello"
              },
              "createdAt": "2026-07-10T20:31:00Z",
              "updatedAt": "2026-07-10T20:31:00Z"
            }
          ]
        }
      ]
    },
    "turns": [
      {
        "id": "turn-1",
        "threadId": "thread-1",
        "status": "completed",
        "input": {
          "prompt": "hello"
        },
        "createdAt": "2026-07-10T20:31:00Z",
        "updatedAt": "2026-07-10T20:32:00Z"
      }
    ],
    "items": [
      {
        "id": "item-1",
        "threadId": "thread-1",
        "turnId": "turn-1",
        "seq": 1,
        "kind": "message",
        "status": "completed",
        "payload": {
          "role": "user",
          "text": "hello"
        },
        "createdAt": "2026-07-10T20:31:00Z",
        "updatedAt": "2026-07-10T20:31:00Z"
      }
    ]
  }
} satisfies BoundResponse<"thread/read">;
export const threadReadResponseResult = threadReadResponse.result satisfies ThreadReadResponse;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
