// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  ThreadMemoryModeSetParams,
  ThreadMemoryModeSetResponse,
  ThreadMetadataUpdateParams,
  ThreadMetadataUpdateResult,
  ThreadNameUpdatedNotification,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const threadMetadataUpdateRequest = {
  "id": "metadata-1",
  "method": "thread/metadata/update",
  "params": {
    "threadId": "thread-1",
    "gitInfo": {
      "sha": "abc123",
      "branch": null,
      "originUrl": "https://example.test/repo.git"
    }
  }
} satisfies BoundRequest<"thread/metadata/update">;
export const threadMetadataUpdateRequestParams = threadMetadataUpdateRequest.params satisfies ThreadMetadataUpdateParams;

export const threadMetadataUpdateLegacyRequest = {
  "id": "metadata-legacy-1",
  "method": "thread/metadata/update",
  "params": {
    "id": "thread-1",
    "metadata": {
      "reviewed": true
    }
  }
} satisfies BoundRequest<"thread/metadata/update">;
export const threadMetadataUpdateLegacyRequestParams = threadMetadataUpdateLegacyRequest.params satisfies ThreadMetadataUpdateParams;

export const threadMetadataUpdateResponse = {
  "id": "metadata-1",
  "result": {
    "thread": {
      "id": "thread-1",
      "title": "Metadata controls",
      "workspace": "/workspace",
      "status": "active",
      "createdAt": "2026-07-10T21:00:00Z",
      "updatedAt": "2026-07-10T21:05:00Z",
      "metadata": {
        "gitInfo": {
          "sha": "abc123",
          "originUrl": "https://example.test/repo.git"
        }
      }
    },
    "metadata": {
      "gitInfo": {
        "sha": "abc123",
        "originUrl": "https://example.test/repo.git"
      }
    }
  }
} satisfies BoundResponse<"thread/metadata/update">;
export const threadMetadataUpdateResponseResult = threadMetadataUpdateResponse.result satisfies ThreadMetadataUpdateResult;

export const threadMemoryModeSetRequest = {
  "id": "memory-mode-1",
  "method": "thread/memoryMode/set",
  "params": {
    "threadId": "thread-1",
    "mode": "disabled"
  }
} satisfies BoundRequest<"thread/memoryMode/set">;
export const threadMemoryModeSetRequestParams = threadMemoryModeSetRequest.params satisfies ThreadMemoryModeSetParams;

export const threadMemoryModeSetLegacyRequest = {
  "id": "memory-mode-legacy-1",
  "method": "thread/memoryMode/set",
  "params": {
    "id": "thread-1",
    "memoryMode": "enabled"
  }
} satisfies BoundRequest<"thread/memoryMode/set">;
export const threadMemoryModeSetLegacyRequestParams = threadMemoryModeSetLegacyRequest.params satisfies ThreadMemoryModeSetParams;

export const threadMemoryModeSetResponse = {
  "id": "memory-mode-1",
  "result": {}
} satisfies BoundResponse<"thread/memoryMode/set">;
export const threadMemoryModeSetResponseResult = threadMemoryModeSetResponse.result satisfies ThreadMemoryModeSetResponse;

export const threadNameUpdatedNotification = {
  "method": "thread/name/updated",
  "params": {
    "threadId": "thread-1",
    "threadName": "Renamed metadata controls"
  }
} satisfies BoundNotification<"thread/name/updated">;
export const threadNameUpdatedNotificationParams = threadNameUpdatedNotification.params satisfies ThreadNameUpdatedNotification;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
