// Code generated by go generate ./appserver/protocol; DO NOT EDIT.

import type {
  BoundNotification,
  BoundRequest,
  BoundResponse,
  ToolRequestUserInputParams,
  ToolRequestUserInputResponse,
} from "../gollem_appserver_protocol";

export const fixtureProtocolVersion = "gollem.appserver.v1" as const;
export const fixtureSchemaVersion = "gollem.appserver.schema.v1" as const;

export const userInputRequest = {
  "id": "interaction-1",
  "method": "item/tool/requestUserInput",
  "params": {
    "threadId": "thread-1",
    "turnId": "turn-1",
    "itemId": "item-tool-1",
    "questions": [
      {
        "id": "call-1",
        "header": "Mode",
        "question": "Choose a mode",
        "isOther": false,
        "isSecret": false,
        "options": [
          {
            "label": "safe",
            "description": ""
          },
          {
            "label": "fast",
            "description": ""
          }
        ]
      }
    ],
    "autoResolutionMs": null,
    "requestId": "interaction-1",
    "startedAtMs": 1783715400000,
    "prompt": "Choose a mode",
    "placeholder": "safe",
    "required": true,
    "options": [
      "safe",
      "fast"
    ],
    "metadata": {
      "source": "runtime"
    },
    "reason": "Choose a mode"
  }
} satisfies BoundRequest<"item/tool/requestUserInput">;
export const userInputRequestParams = userInputRequest.params satisfies ToolRequestUserInputParams;

export const userInputResponse = {
  "id": "interaction-1",
  "result": {
    "answers": {
      "call-1": {
        "answers": [
          "safe"
        ]
      }
    }
  }
} satisfies BoundResponse<"item/tool/requestUserInput">;
export const userInputResponseResult = userInputResponse.result satisfies ToolRequestUserInputResponse;

// @ts-expect-error request methods cannot use notification envelopes.
export type RejectRequestAsNotification = BoundNotification<"daemon/status">;
// @ts-expect-error notification methods cannot use request envelopes.
export type RejectNotificationAsRequest = BoundRequest<"item/started">;
