package protocol

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"slices"
	"sort"
	"strings"
	"unicode"
)

const typeScriptOptionalNonNullKeyword = "x-gollem-typescript-optional-nonnull"
const typeScriptBigIntKeyword = "x-gollem-typescript-bigint"

const typeScriptGeneratedHeader = "// Code generated by go generate ./appserver/protocol; DO NOT EDIT.\n\n"

// MarshalTypeScript generates the TypeScript binding for the current public
// app-server schema and binding metadata.
func MarshalTypeScript() ([]byte, error) {
	schema := JSONSchema()
	defs, ok := schema["$defs"].(Schema)
	if !ok {
		return nil, fmt.Errorf("protocol schema definitions have type %T", schema["$defs"])
	}

	var out bytes.Buffer
	out.WriteString(typeScriptGeneratedHeader)
	fmt.Fprintf(&out, "export const protocolVersion = %s as const;\n", typeScriptString(ProtocolVersion))
	fmt.Fprintf(&out, "export const schemaVersion = %s as const;\n\n", typeScriptString(SchemaVersion))
	writeTypeScriptProtocolMetadata(&out)

	names := make([]string, 0, len(defs))
	for name := range defs {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		definition := defs[name]
		if name == "ApplyPatchApprovalParams" || name == "MigrationDetails" ||
			name == "ExternalAgentConfigMigrationItem" ||
			name == "ExternalAgentConfigImportItemTypeFailure" ||
			name == "ExternalAgentConfigImportItemTypeSuccess" ||
			name == "ExecCommandApprovalParams" ||
			name == "FuzzyFileSearchParams" || name == "FuzzyFileSearchResult" ||
			name == "HookRunSummary" || name == "HookStartedNotification" ||
			name == "HookCompletedNotification" || name == "HookMetadata" ||
			name == "GuardianApprovalReview" || name == "ParsedCommand" ||
			name == "ItemGuardianApprovalReviewCompletedNotification" ||
			name == "ItemGuardianApprovalReviewStartedNotification" {
			// Rust accepts omitted serde default/Option fields while generated
			// TypeScript requires callers to provide their canonical values.
			schema, _ := typeScriptSchema(definition)
			renderSchema := make(Schema, len(schema)+1)
			for key, value := range schema {
				renderSchema[key] = value
			}
			schema = renderSchema
			switch name {
			case "ApplyPatchApprovalParams":
				schema["required"] = []string{
					"conversationId", "callId", "fileChanges", "reason", "grantRoot",
				}
			case "ExecCommandApprovalParams":
				schema["required"] = []string{
					"conversationId", "callId", "approvalId", "command", "cwd", "reason", "parsedCmd",
				}
			case "MigrationDetails":
				schema["required"] = []string{
					"plugins", "skills", "sessions", "mcpServers", "hooks", "subagents", "commands",
				}
			case "ExternalAgentConfigMigrationItem":
				schema["required"] = []string{"itemType", "description", "cwd", "details"}
			case "ExternalAgentConfigImportItemTypeFailure":
				schema["required"] = []string{
					"itemType", "errorType", "failureStage", "message", "cwd", "source",
				}
			case "ExternalAgentConfigImportItemTypeSuccess":
				schema["required"] = []string{"itemType", "cwd", "source", "target"}
			case "FuzzyFileSearchParams":
				schema["required"] = []string{"query", "roots", "cancellationToken"}
			case "FuzzyFileSearchResult":
				schema["required"] = []string{
					"root", "path", "match_type", "file_name", "score", "indices",
				}
			case "HookRunSummary":
				schema["required"] = []string{
					"id", "eventName", "handlerType", "executionMode", "scope", "sourcePath",
					"source", "displayOrder", "status", "statusMessage", "startedAt",
					"completedAt", "durationMs", "entries",
				}
			case "HookStartedNotification", "HookCompletedNotification":
				schema["required"] = []string{"threadId", "turnId", "run"}
			case "HookMetadata":
				schema["required"] = []string{
					"key", "eventName", "handlerType", "matcher", "command", "timeoutSec",
					"statusMessage", "sourcePath", "source", "pluginId", "displayOrder",
					"enabled", "isManaged", "currentHash", "trustStatus",
				}
			case "GuardianApprovalReview":
				schema["required"] = []string{
					"status", "riskLevel", "userAuthorization", "rationale",
				}
			case "ParsedCommand":
				variants := schema["oneOf"].([]any)
				for index, required := range [][]string{
					{"type", "cmd", "name", "path"},
					{"type", "cmd", "path"},
					{"type", "cmd", "query", "path"},
					{"type", "cmd"},
				} {
					variant := variants[index].(Schema)
					copy := make(Schema, len(variant))
					for key, value := range variant {
						copy[key] = value
					}
					copy["required"] = required
					variants[index] = copy
				}
			case "ItemGuardianApprovalReviewCompletedNotification":
				schema["required"] = []string{
					"threadId", "turnId", "startedAtMs", "completedAtMs", "reviewId",
					"targetItemId", "decisionSource", "review", "action",
				}
			case "ItemGuardianApprovalReviewStartedNotification":
				schema["required"] = []string{
					"threadId", "turnId", "startedAtMs", "reviewId", "targetItemId", "review", "action",
				}
			}
			definition = schema
		}
		if name == "ApplyPatchApprovalParams" {
			// ts-rs models HashMap values with optional mapped keys. Keep this
			// render-only hint out of the exact public JSON Schema.
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"fileChanges": Schema{
					"type":                             "object",
					"additionalProperties":             Schema{"$ref": "#/$defs/FileChange"},
					"x-gollem-typescript-optional-map": true,
				},
			})
		}
		if name == "ExternalAgentConfigImportHistory" {
			// ts-rs maps this Rust i64 to bigint. Apply the hint only to a
			// render copy so the public JSON Schema remains exact.
			definition = typeScriptDefinitionWithBigIntProperties(definition, "completedAtMs")
		}
		if name == "HookRunSummary" {
			// ts-rs maps each Rust i64 field to bigint, including nullable i64
			// options. Keep these hints out of the public JSON Schema.
			definition = typeScriptDefinitionWithBigIntProperties(
				definition, "displayOrder", "startedAt", "completedAt", "durationMs",
			)
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"source":        Schema{"$ref": "#/$defs/HookSource"},
				"statusMessage": Schema{"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}}},
			})
		}
		if name == "HookMetadata" {
			// ts-rs maps Rust u64 and i64 fields to bigint. Keep the render hints
			// out of the exact public JSON Schema.
			definition = typeScriptDefinitionWithBigIntProperties(
				definition, "timeoutSec", "displayOrder",
			)
			nullableString := Schema{
				"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}},
			}
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"matcher": nullableString, "command": nullableString,
				"statusMessage": nullableString, "pluginId": nullableString,
			})
		}
		if name == "HookStartedNotification" || name == "HookCompletedNotification" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"turnId": Schema{"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}}},
			})
		}
		if name == "GuardianApprovalReview" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"rationale": Schema{"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}}},
			})
		}
		if name == "GuardianApprovalReviewAction" {
			definition = guardianApprovalReviewActionTypeScriptSchema(definition)
		}
		if name == "FileChange" {
			definition = fileChangeTypeScriptSchema(definition)
		}
		if name == "ItemGuardianApprovalReviewCompletedNotification" ||
			name == "ItemGuardianApprovalReviewStartedNotification" {
			definition = typeScriptDefinitionWithPropertySchemas(definition, Schema{
				"targetItemId": Schema{
					"anyOf": []any{Schema{"type": "string"}, Schema{"type": "null"}},
				},
			})
		}
		typeName, err := typeScriptType(definition, 0)
		if err != nil {
			return nil, fmt.Errorf("generate TypeScript definition %s: %w", name, err)
		}
		fmt.Fprintf(&out, "export type %s = %s;\n\n", name, typeName)
	}

	writeTypeScriptWireBindings(&out)
	writeTypeScriptItemBindings(&out)
	return out.Bytes(), nil
}

func writeTypeScriptProtocolMetadata(out *bytes.Buffer) {
	out.WriteString("export type ProtocolSurface =\n")
	for i, surface := range []Surface{
		SurfaceClientRequest,
		SurfaceServerNotification,
		SurfaceServerRequest,
		SurfaceClientNotification,
		SurfaceGollemExtension,
	} {
		terminator := "\n"
		if i == 4 {
			terminator = ";\n\n"
		}
		fmt.Fprintf(out, "  | %s%s", typeScriptString(string(surface)), terminator)
	}
	out.WriteString("export type ProtocolMethodState =\n")
	states := []MethodState{
		MethodImplemented,
		MethodBlocked,
		MethodDeferredStub,
		MethodRenamedEquivalent,
		MethodNotApplicable,
	}
	for i, state := range states {
		terminator := "\n"
		if i == len(states)-1 {
			terminator = ";\n\n"
		}
		fmt.Fprintf(out, "  | %s%s", typeScriptString(string(state)), terminator)
	}
	out.WriteString("export type ProtocolMethodInfo = {\n")
	out.WriteString("  \"method\": string;\n")
	out.WriteString("  \"surface\": ProtocolSurface;\n")
	out.WriteString("  \"state\": ProtocolMethodState;\n")
	out.WriteString("  \"source\"?: string;\n")
	out.WriteString("};\n\n")

	methods := Methods()
	out.WriteString("export const protocolMethods = [\n")
	for _, method := range methods {
		fmt.Fprintf(out, "  { \"method\": %s, \"surface\": %s, \"state\": %s", typeScriptString(method.Method), typeScriptString(string(method.Surface)), typeScriptString(string(method.State)))
		if method.Source != "" {
			fmt.Fprintf(out, ", \"source\": %s", typeScriptString(method.Source))
		}
		out.WriteString(" },\n")
	}
	out.WriteString("] as const satisfies readonly ProtocolMethodInfo[];\n\n")

	writeTypeScriptMethodUnion(out, "ClientRequestMethod", MethodsBySurface(SurfaceClientRequest))
	writeTypeScriptMethodUnion(out, "ServerNotificationMethod", MethodsBySurface(SurfaceServerNotification))
	writeTypeScriptMethodUnion(out, "ServerRequestMethod", MethodsBySurface(SurfaceServerRequest))
	writeTypeScriptMethodUnion(out, "ClientNotificationMethod", MethodsBySurface(SurfaceClientNotification))
	writeTypeScriptMethodUnion(out, "GollemExtensionMethod", MethodsBySurface(SurfaceGollemExtension))
	out.WriteString("export type KnownMethod =\n")
	out.WriteString("  | ClientRequestMethod\n")
	out.WriteString("  | ServerNotificationMethod\n")
	out.WriteString("  | ServerRequestMethod\n")
	out.WriteString("  | ClientNotificationMethod\n")
	out.WriteString("  | GollemExtensionMethod;\n\n")
}

func writeTypeScriptMethodUnion(out *bytes.Buffer, name string, methods []MethodInfo) {
	fmt.Fprintf(out, "export type %s =", name)
	if len(methods) == 0 {
		out.WriteString(" never;\n\n")
		return
	}
	out.WriteByte('\n')
	for i, method := range methods {
		terminator := "\n"
		if i == len(methods)-1 {
			terminator = ";\n\n"
		}
		fmt.Fprintf(out, "  | %s%s", typeScriptString(method.Method), terminator)
	}
}

func writeTypeScriptWireBindings(out *bytes.Buffer) {
	bindings := WireTypeBindings()
	out.WriteString("export type WireTypeBinding = {\n")
	out.WriteString("  \"method\": KnownMethod;\n")
	out.WriteString("  \"surface\": ProtocolSurface;\n")
	out.WriteString("  \"params\"?: readonly string[];\n")
	out.WriteString("  \"result\"?: readonly string[];\n")
	out.WriteString("};\n\n")
	out.WriteString("export const wireTypeBindings = [\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  { \"method\": %s, \"surface\": %s", typeScriptString(binding.Method), typeScriptString(string(binding.Surface)))
		if len(binding.Params) > 0 {
			fmt.Fprintf(out, ", \"params\": %s", typeScriptStringArray(binding.Params))
		}
		if len(binding.Result) > 0 {
			fmt.Fprintf(out, ", \"result\": %s", typeScriptStringArray(binding.Result))
		}
		out.WriteString(" },\n")
	}
	out.WriteString("] as const satisfies readonly WireTypeBinding[];\n\n")

	out.WriteString("export interface MethodParamsByName {\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  %s: %s;\n", typeScriptString(binding.Method), typeScriptTypeUnion(binding.Params, "undefined"))
	}
	out.WriteString("}\n\n")
	out.WriteString("export interface MethodResultsByName {\n")
	for _, binding := range bindings {
		if len(binding.Result) == 0 {
			continue
		}
		fmt.Fprintf(out, "  %s: %s;\n", typeScriptString(binding.Method), typeScriptTypeUnion(binding.Result, "never"))
	}
	out.WriteString("}\n\n")
	out.WriteString("export type BoundRequestMethod = Extract<\n")
	out.WriteString("  keyof MethodParamsByName,\n")
	out.WriteString("  ClientRequestMethod | ServerRequestMethod | GollemExtensionMethod\n")
	out.WriteString(">;\n")
	out.WriteString("export type BoundNotificationMethod = Extract<\n")
	out.WriteString("  keyof MethodParamsByName,\n")
	out.WriteString("  ServerNotificationMethod | ClientNotificationMethod\n")
	out.WriteString(">;\n\n")
	out.WriteString("export type ParamsFor<M extends keyof MethodParamsByName> = MethodParamsByName[M];\n")
	out.WriteString("export type ResultFor<M extends keyof MethodResultsByName> = MethodResultsByName[M];\n\n")
	out.WriteString("export type BoundRequest<M extends BoundRequestMethod> =\n")
	out.WriteString("  MethodParamsByName[M] extends undefined\n")
	out.WriteString("    ? { \"id\": RequestID; \"method\": M; \"params\"?: never }\n")
	out.WriteString("    : { \"id\": RequestID; \"method\": M; \"params\": MethodParamsByName[M] };\n\n")
	out.WriteString("export type BoundNotification<M extends BoundNotificationMethod> =\n")
	out.WriteString("  MethodParamsByName[M] extends undefined\n")
	out.WriteString("    ? { \"method\": M; \"params\"?: never }\n")
	out.WriteString("    : { \"method\": M; \"params\": MethodParamsByName[M] };\n\n")
	out.WriteString("export type BoundResponse<M extends keyof MethodResultsByName> =\n")
	out.WriteString("  | { \"id\": RequestID; \"result\": MethodResultsByName[M]; \"error\"?: never }\n")
	out.WriteString("  | { \"id\": RequestID; \"result\"?: never; \"error\": Error };\n\n")
}

func writeTypeScriptItemBindings(out *bytes.Buffer) {
	bindings := ItemPayloadBindings()
	out.WriteString("export type ItemPayloadBinding = {\n")
	out.WriteString("  \"kind\": string;\n")
	out.WriteString("  \"type\": string;\n")
	out.WriteString("};\n\n")
	out.WriteString("export const itemPayloadBindings = [\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  { \"kind\": %s, \"type\": %s },\n", typeScriptString(binding.Kind), typeScriptString(binding.Type))
	}
	out.WriteString("] as const satisfies readonly ItemPayloadBinding[];\n\n")
	out.WriteString("export interface ItemPayloadByKind {\n")
	for _, binding := range bindings {
		fmt.Fprintf(out, "  %s: %s;\n", typeScriptString(binding.Kind), binding.Type)
	}
	out.WriteString("}\n\n")
	out.WriteString("export type KnownItemKind = keyof ItemPayloadByKind;\n")
	out.WriteString("export type KnownItemPayload = ItemPayloadByKind[KnownItemKind];\n")
	out.WriteString("export type KnownTimelineItem = {\n")
	out.WriteString("  [K in KnownItemKind]: Omit<TimelineItem, \"kind\" | \"payload\"> & {\n")
	out.WriteString("    \"kind\": K;\n")
	out.WriteString("    \"payload\": ItemPayloadByKind[K];\n")
	out.WriteString("  };\n")
	out.WriteString("}[KnownItemKind];\n")
}

func typeScriptDefinitionWithBigIntProperties(definition any, names ...string) Schema {
	schema, _ := typeScriptSchema(definition)
	renderSchema := make(Schema, len(schema))
	for key, value := range schema {
		renderSchema[key] = value
	}
	properties, _ := typeScriptSchema(schema["properties"])
	renderProperties := make(Schema, len(properties))
	for key, value := range properties {
		renderProperties[key] = value
	}
	for _, name := range names {
		property, _ := typeScriptSchema(properties[name])
		renderProperty := make(Schema, len(property)+1)
		for key, value := range property {
			renderProperty[key] = value
		}
		renderProperty[typeScriptBigIntKeyword] = true
		renderProperties[name] = renderProperty
	}
	renderSchema["properties"] = renderProperties
	return renderSchema
}

func typeScriptDefinitionWithPropertySchemas(definition any, replacements Schema) Schema {
	schema, _ := typeScriptSchema(definition)
	renderSchema := make(Schema, len(schema))
	for key, value := range schema {
		renderSchema[key] = value
	}
	properties, _ := typeScriptSchema(schema["properties"])
	renderProperties := make(Schema, len(properties))
	for key, value := range properties {
		renderProperties[key] = value
	}
	for name, replacement := range replacements {
		renderProperties[name] = replacement
	}
	renderSchema["properties"] = renderProperties
	return renderSchema
}

func guardianApprovalReviewActionTypeScriptSchema(definition any) Schema {
	schema, _ := typeScriptSchema(definition)
	renderSchema := make(Schema, len(schema))
	for key, value := range schema {
		renderSchema[key] = value
	}
	variants, _ := typeScriptAnySlice(schema["oneOf"])
	renderVariants := make([]any, 0, len(variants))
	for _, rawVariant := range variants {
		variant, _ := typeScriptSchema(rawVariant)
		renderVariant := make(Schema, len(variant))
		for key, value := range variant {
			renderVariant[key] = value
		}
		properties, _ := typeScriptSchema(variant["properties"])
		renderProperties := make(Schema, len(properties))
		for key, value := range properties {
			renderProperties[key] = value
		}
		typeSchema, _ := typeScriptSchema(properties["type"])
		tags, _ := typeScriptAnySlice(typeSchema["enum"])
		required := append([]string(nil), variant["required"].([]string)...)
		var nullableFields []string
		if len(tags) == 1 {
			switch tags[0] {
			case "mcpToolCall":
				nullableFields = []string{"connectorId", "connectorName", "toolTitle"}
			case "requestPermissions":
				nullableFields = []string{"reason"}
			}
		}
		for _, field := range nullableFields {
			required = append(required, field)
			renderProperties[field] = Schema{"anyOf": []any{
				Schema{"type": "string"}, Schema{"type": "null"},
			}}
		}
		renderVariant["properties"] = renderProperties
		renderVariant["required"] = required
		renderVariants = append(renderVariants, renderVariant)
	}
	renderSchema["oneOf"] = renderVariants
	return renderSchema
}

func fileChangeTypeScriptSchema(definition any) Schema {
	schema, _ := typeScriptSchema(definition)
	renderSchema := make(Schema, len(schema))
	for key, value := range schema {
		renderSchema[key] = value
	}
	variants, _ := typeScriptAnySlice(schema["oneOf"])
	renderVariants := make([]any, 0, len(variants))
	for _, rawVariant := range variants {
		variant, _ := typeScriptSchema(rawVariant)
		renderVariant := make(Schema, len(variant))
		for key, value := range variant {
			renderVariant[key] = value
		}
		properties, _ := typeScriptSchema(variant["properties"])
		typeSchema, _ := typeScriptSchema(properties["type"])
		tags, _ := typeScriptAnySlice(typeSchema["enum"])
		if len(tags) == 1 && tags[0] == "update" {
			renderProperties := make(Schema, len(properties))
			for key, value := range properties {
				renderProperties[key] = value
			}
			renderProperties["move_path"] = Schema{"anyOf": []any{
				Schema{"type": "string"}, Schema{"type": "null"},
			}}
			required := append([]string(nil), variant["required"].([]string)...)
			required = append(required, "move_path")
			renderVariant["properties"] = renderProperties
			renderVariant["required"] = required
		}
		renderVariants = append(renderVariants, renderVariant)
	}
	renderSchema["oneOf"] = renderVariants
	return renderSchema
}

func typeScriptType(value any, indent int) (string, error) {
	schema, ok := typeScriptSchema(value)
	if !ok || len(schema) == 0 {
		return "unknown", nil
	}
	if bigint, _ := schema[typeScriptBigIntKeyword].(bool); bigint {
		if schema["type"] == "integer" {
			return "bigint", nil
		}
		types, ok := typeScriptAnySlice(schema["type"])
		if !ok {
			return "", errors.New("TypeScript bigint schema must have integer type")
		}
		parts := make([]string, 0, len(types))
		for _, value := range types {
			switch value {
			case "integer":
				parts = appendUniqueTypeScript(parts, "bigint")
			case "null":
				parts = appendUniqueTypeScript(parts, "null")
			default:
				return "", errors.New("TypeScript bigint schema type array must contain only integer and null")
			}
		}
		if !slices.Contains(parts, "bigint") {
			return "", errors.New("TypeScript bigint schema type array must contain integer")
		}
		return strings.Join(parts, " | "), nil
	}
	if ref, ok := schema["$ref"].(string); ok {
		const prefix = "#/$defs/"
		if !strings.HasPrefix(ref, prefix) || len(ref) == len(prefix) {
			return "", fmt.Errorf("unsupported ref %q", ref)
		}
		return strings.TrimPrefix(ref, prefix), nil
	}
	if values, ok := typeScriptAnySlice(schema["enum"]); ok {
		return typeScriptLiteralUnion(values), nil
	}
	for _, keyword := range []string{"oneOf", "anyOf"} {
		if variants, ok := typeScriptAnySlice(schema[keyword]); ok {
			parts := make([]string, 0, len(variants))
			for _, variant := range variants {
				part, err := typeScriptType(variant, indent)
				if err != nil {
					return "", err
				}
				parts = appendUniqueTypeScript(parts, part)
			}
			if len(parts) == 0 {
				return "never", nil
			}
			return strings.Join(parts, " | "), nil
		}
	}

	typeName, _ := schema["type"].(string)
	switch typeName {
	case "string":
		return "string", nil
	case "integer", "number":
		return "number", nil
	case "boolean":
		return "boolean", nil
	case "null":
		return "null", nil
	case "array":
		item, err := typeScriptType(schema["items"], indent)
		if err != nil {
			return "", err
		}
		return "Array<" + item + ">", nil
	case "object":
		return typeScriptObjectType(schema, indent)
	case "":
		return "unknown", nil
	default:
		return "", fmt.Errorf("unsupported schema type %q", typeName)
	}
}

func typeScriptObjectType(schema Schema, indent int) (string, error) {
	properties, _ := typeScriptSchema(schema["properties"])
	required := typeScriptRequiredNames(schema["required"])
	additional, additionalIsSchema := typeScriptSchema(schema["additionalProperties"])
	additionalAllowed := true
	if allowed, ok := schema["additionalProperties"].(bool); ok {
		additionalAllowed = allowed
	}
	if len(properties) == 0 {
		if additionalIsSchema {
			valueType, err := typeScriptType(additional, indent)
			if err != nil {
				return "", err
			}
			if recursive, _ := schema["x-gollem-typescript-recursive-map"].(bool); recursive {
				return "{ [key: string]: " + valueType + " }", nil
			}
			if optional, _ := schema["x-gollem-typescript-optional-map"].(bool); optional {
				return "{ [key in string]?: " + valueType + " }", nil
			}
			return "Record<string, " + valueType + ">", nil
		}
		if !additionalAllowed {
			return "Record<string, never>", nil
		}
		return "Record<string, unknown>", nil
	}

	names := make([]string, 0, len(properties))
	for name := range properties {
		names = append(names, name)
	}
	sort.Strings(names)
	baseIndent := strings.Repeat("  ", indent)
	fieldIndent := strings.Repeat("  ", indent+1)
	var out strings.Builder
	out.WriteString("{\n")
	for _, name := range names {
		fieldValue := properties[name]
		fieldSchema, _ := typeScriptSchema(fieldValue)
		var fieldType string
		var err error
		if optionalNonNull, _ := fieldSchema[typeScriptOptionalNonNullKeyword].(bool); optionalNonNull {
			fieldType, err = typeScriptOptionalNonNullType(fieldSchema, indent+1)
		} else {
			fieldType, err = typeScriptType(fieldValue, indent+1)
		}
		if err != nil {
			return "", fmt.Errorf("property %s: %w", name, err)
		}
		optional := "?"
		if required[name] {
			optional = ""
		}
		fmt.Fprintf(&out, "%s%s%s: %s;\n", fieldIndent, typeScriptString(name), optional, fieldType)
	}
	out.WriteString(baseIndent)
	out.WriteByte('}')
	objectType := out.String()
	if additionalIsSchema {
		valueType, err := typeScriptType(additional, indent)
		if err != nil {
			return "", err
		}
		additionalType := "Record<string, " + valueType + ">"
		if optional, _ := schema["x-gollem-typescript-optional-map"].(bool); optional {
			additionalType = "{ [key in string]?: " + valueType + " }"
		}
		return "(" + objectType + " & " + additionalType + ")", nil
	}
	ignoreAdditional, _ := schema["x-gollem-typescript-ignore-additional-properties"].(bool)
	if additionalAllowed && !ignoreAdditional {
		return "(" + objectType + " & Record<string, unknown>)", nil
	}
	return objectType, nil
}

func typeScriptOptionalNonNullType(schema Schema, indent int) (string, error) {
	variants, ok := typeScriptAnySlice(schema["anyOf"])
	if !ok {
		return "", errors.New("optional non-null TypeScript schema requires anyOf")
	}
	nonNull := make([]any, 0, len(variants))
	for _, variant := range variants {
		variantSchema, _ := typeScriptSchema(variant)
		if variantSchema["type"] == "null" {
			continue
		}
		nonNull = append(nonNull, variant)
	}
	if len(nonNull) == 0 {
		return "", errors.New("optional non-null TypeScript schema has no non-null variant")
	}
	if len(nonNull) == 1 {
		return typeScriptType(nonNull[0], indent)
	}
	return typeScriptType(Schema{"anyOf": nonNull}, indent)
}

func typeScriptSchema(value any) (Schema, bool) {
	switch typed := value.(type) {
	case Schema:
		return typed, true
	case map[string]any:
		return Schema(typed), true
	default:
		return nil, false
	}
}

func typeScriptAnySlice(value any) ([]any, bool) {
	typed, ok := value.([]any)
	return typed, ok
}

func typeScriptRequiredNames(value any) map[string]bool {
	out := make(map[string]bool)
	switch typed := value.(type) {
	case []string:
		for _, name := range typed {
			out[name] = true
		}
	case []any:
		for _, item := range typed {
			if name, ok := item.(string); ok {
				out[name] = true
			}
		}
	}
	return out
}

func typeScriptLiteralUnion(values []any) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		encoded, err := json.Marshal(value)
		if err != nil {
			parts = append(parts, "unknown")
			continue
		}
		parts = appendUniqueTypeScript(parts, string(encoded))
	}
	if len(parts) == 0 {
		return "never"
	}
	return strings.Join(parts, " | ")
}

func appendUniqueTypeScript(values []string, value string) []string {
	for _, existing := range values {
		if existing == value {
			return values
		}
	}
	return append(values, value)
}

func typeScriptTypeUnion(names []string, empty string) string {
	if len(names) == 0 {
		return empty
	}
	return strings.Join(names, " | ")
}

func typeScriptString(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func typeScriptStringArray(values []string) string {
	encoded := make([]string, 0, len(values))
	for _, value := range values {
		encoded = append(encoded, typeScriptString(value))
	}
	return "[" + strings.Join(encoded, ", ") + "]"
}

type typeScriptFixtureDocument struct {
	ProtocolVersion string                  `json:"protocolVersion"`
	SchemaVersion   string                  `json:"schemaVersion"`
	Cases           []typeScriptFixtureCase `json:"cases"`
}

type typeScriptFixtureCase struct {
	Name        string          `json:"name"`
	Surface     Surface         `json:"surface"`
	Method      string          `json:"method"`
	Envelope    string          `json:"envelope,omitempty"`
	ParamsType  string          `json:"paramsType,omitempty"`
	ResultType  string          `json:"resultType,omitempty"`
	PayloadType string          `json:"payloadType,omitempty"`
	Message     json.RawMessage `json:"message"`
}

type permissionProfileTypeScriptFixtureDocument struct {
	ProtocolVersion string          `json:"protocolVersion"`
	SchemaVersion   string          `json:"schemaVersion"`
	Request         json.RawMessage `json:"request"`
	Response        json.RawMessage `json:"response"`
}

// MarshalPermissionProfileTypeScriptFixture generates a strict compile fixture
// for the exported public permission types without creating a live binding.
func MarshalPermissionProfileTypeScriptFixture(data []byte) ([]byte, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var fixture permissionProfileTypeScriptFixtureDocument
	if err := decoder.Decode(&fixture); err != nil {
		return nil, fmt.Errorf("decode permission profile fixture: %w", err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil {
			return nil, errors.New("permission profile fixture must contain one JSON value")
		}
		return nil, err
	}
	if fixture.ProtocolVersion != ProtocolVersion || fixture.SchemaVersion != SchemaVersion {
		return nil, fmt.Errorf("fixture versions %s/%s do not match %s/%s", fixture.ProtocolVersion, fixture.SchemaVersion, ProtocolVersion, SchemaVersion)
	}
	var request, response bytes.Buffer
	if err := json.Indent(&request, fixture.Request, "", "  "); err != nil {
		return nil, fmt.Errorf("format permission request: %w", err)
	}
	if err := json.Indent(&response, fixture.Response, "", "  "); err != nil {
		return nil, fmt.Errorf("format permission response: %w", err)
	}

	var out bytes.Buffer
	out.WriteString(typeScriptGeneratedHeader)
	out.WriteString("import type {\n")
	for _, name := range []string{
		"ActivePermissionProfile",
		"AdditionalPermissionProfile",
		"FileSystemAccessMode",
		"FileSystemPath",
		"MethodResultsByName",
		"PermissionGrantScope",
		"PermissionsRequestApprovalParams",
		"PermissionsRequestApprovalResponse",
	} {
		fmt.Fprintf(&out, "  %s,\n", name)
	}
	out.WriteString("} from \"../gollem_appserver_protocol\";\n\n")
	fmt.Fprintf(&out, "export const fixtureProtocolVersion = %s as const;\n", typeScriptString(fixture.ProtocolVersion))
	fmt.Fprintf(&out, "export const fixtureSchemaVersion = %s as const;\n\n", typeScriptString(fixture.SchemaVersion))
	fmt.Fprintf(&out, "export const permissionProfileRequest = %s satisfies PermissionsRequestApprovalParams;\n\n", request.String())
	fmt.Fprintf(&out, "export const permissionProfileResponse = %s satisfies PermissionsRequestApprovalResponse;\n\n", response.String())
	out.WriteString("export const activePermissionProfile = { id: \":workspace\", extends: null } satisfies ActivePermissionProfile;\n")
	out.WriteString("export const additionalPermissionProfile = { network: null, fileSystem: null } satisfies AdditionalPermissionProfile;\n\n")
	out.WriteString("// @ts-expect-error filesystem access modes are closed.\n")
	out.WriteString("export const rejectInvalidFilesystemAccess = \"execute\" satisfies FileSystemAccessMode;\n")
	out.WriteString("// @ts-expect-error filesystem path variants cannot cross fields.\n")
	out.WriteString("export const rejectCrossedFilesystemPath = { type: \"path\", pattern: \"*.go\" } satisfies FileSystemPath;\n")
	out.WriteString("// @ts-expect-error permission grant scopes are closed.\n")
	out.WriteString("export const rejectInvalidPermissionScope = \"workspace\" satisfies PermissionGrantScope;\n")
	out.WriteString("// @ts-expect-error canonical permission requests require nullable environmentId.\n")
	out.WriteString("export const rejectMissingPermissionEnvironment = { threadId: \"t\", turnId: \"u\", itemId: \"i\", startedAtMs: 1, cwd: \"/workspace\", reason: null, permissions: { network: null, fileSystem: null } } satisfies PermissionsRequestApprovalParams;\n")
	out.WriteString("// @ts-expect-error canonical permission responses require scope.\n")
	out.WriteString("export const rejectMissingPermissionScope = { permissions: {} } satisfies PermissionsRequestApprovalResponse;\n")
	out.WriteString("// @ts-expect-error the incompatible live permission result remains unbound.\n")
	out.WriteString("export type RejectPermissionResultBinding = MethodResultsByName[\"item/permissions/requestApproval\"];\n")
	return out.Bytes(), nil
}

// MarshalTypeScriptFixture converts the versioned JSON wire examples into a
// TypeScript compile fixture using the generated method and payload bindings.
func MarshalTypeScriptFixture(data []byte) ([]byte, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var fixture typeScriptFixtureDocument
	if err := decoder.Decode(&fixture); err != nil {
		return nil, fmt.Errorf("decode runtime wire fixture: %w", err)
	}
	if fixture.ProtocolVersion != ProtocolVersion || fixture.SchemaVersion != SchemaVersion {
		return nil, fmt.Errorf("fixture versions %s/%s do not match %s/%s", fixture.ProtocolVersion, fixture.SchemaVersion, ProtocolVersion, SchemaVersion)
	}

	imports := map[string]bool{
		"BoundNotification": true,
		"BoundRequest":      true,
		"BoundResponse":     true,
	}
	for _, fixtureCase := range fixture.Cases {
		for _, name := range []string{fixtureCase.ParamsType, fixtureCase.ResultType, fixtureCase.PayloadType} {
			if name != "" {
				imports[name] = true
			}
		}
	}
	importNames := make([]string, 0, len(imports))
	for name := range imports {
		importNames = append(importNames, name)
	}
	sort.Strings(importNames)

	var out bytes.Buffer
	out.WriteString(typeScriptGeneratedHeader)
	out.WriteString("import type {\n")
	for _, name := range importNames {
		fmt.Fprintf(&out, "  %s,\n", name)
	}
	out.WriteString("} from \"../gollem_appserver_protocol\";\n\n")
	fmt.Fprintf(&out, "export const fixtureProtocolVersion = %s as const;\n", typeScriptString(fixture.ProtocolVersion))
	fmt.Fprintf(&out, "export const fixtureSchemaVersion = %s as const;\n\n", typeScriptString(fixture.SchemaVersion))

	seen := make(map[string]bool, len(fixture.Cases))
	hasInitialize := false
	hasInitialized := false
	hasFilesystem := false
	for _, fixtureCase := range fixture.Cases {
		identifier := typeScriptIdentifier(fixtureCase.Name)
		if identifier == "" || seen[identifier] {
			return nil, fmt.Errorf("invalid or duplicate fixture identifier for %q", fixtureCase.Name)
		}
		seen[identifier] = true
		info, ok := LookupMethod(fixtureCase.Method)
		if !ok || info.Surface != fixtureCase.Surface {
			return nil, fmt.Errorf("fixture %s references invalid method surface %s/%s", fixtureCase.Name, fixtureCase.Surface, fixtureCase.Method)
		}
		if !typeScriptFixtureBindingExists(fixtureCase) {
			return nil, fmt.Errorf("fixture %s type metadata is not bound to %s", fixtureCase.Name, fixtureCase.Method)
		}
		hasInitialize = hasInitialize || fixtureCase.Method == "initialize"
		hasInitialized = hasInitialized || fixtureCase.Method == "initialized"
		hasFilesystem = hasFilesystem || strings.HasPrefix(fixtureCase.Method, "fs/")

		var message bytes.Buffer
		if err := json.Indent(&message, fixtureCase.Message, "", "  "); err != nil {
			return nil, fmt.Errorf("format fixture %s: %w", fixtureCase.Name, err)
		}
		envelope, err := typeScriptFixtureEnvelope(fixtureCase)
		if err != nil {
			return nil, fmt.Errorf("fixture %s: %w", fixtureCase.Name, err)
		}
		bindingType := ""
		switch envelope {
		case "notification":
			bindingType = "BoundNotification<" + typeScriptString(fixtureCase.Method) + ">"
		case "request":
			bindingType = "BoundRequest<" + typeScriptString(fixtureCase.Method) + ">"
		case "response":
			bindingType = "BoundResponse<" + typeScriptString(fixtureCase.Method) + ">"
		}
		fmt.Fprintf(&out, "export const %s = %s satisfies %s;\n", identifier, message.String(), bindingType)
		if fixtureCase.ParamsType != "" {
			fmt.Fprintf(&out, "export const %sParams = %s.params satisfies %s;\n", identifier, identifier, fixtureCase.ParamsType)
		}
		if fixtureCase.ResultType != "" {
			fmt.Fprintf(&out, "export const %sResult = %s.result satisfies %s;\n", identifier, identifier, fixtureCase.ResultType)
		}
		if fixtureCase.PayloadType != "" {
			payload, err := typeScriptFixturePayload(fixtureCase.Message)
			if err != nil {
				return nil, fmt.Errorf("fixture %s payload: %w", fixtureCase.Name, err)
			}
			fmt.Fprintf(&out, "export const %sPayload = %s satisfies %s;\n", identifier, payload, fixtureCase.PayloadType)
		}
		out.WriteByte('\n')
	}
	out.WriteString("// @ts-expect-error request methods cannot use notification envelopes.\n")
	out.WriteString("export type RejectRequestAsNotification = BoundNotification<\"daemon/status\">;\n")
	out.WriteString("// @ts-expect-error notification methods cannot use request envelopes.\n")
	out.WriteString("export type RejectNotificationAsRequest = BoundRequest<\"item/started\">;\n")
	if hasInitialize {
		out.WriteString("// @ts-expect-error initialize requires clientInfo.\n")
		out.WriteString("export const rejectInitializeWithoutClientInfo = { \"capabilities\": {} } satisfies InitializeParams;\n")
		out.WriteString("// @ts-expect-error initialize requires clientInfo.version.\n")
		out.WriteString("export const rejectInitializeWithoutClientVersion = { \"clientInfo\": { \"name\": \"client\" } } satisfies InitializeParams;\n")
	}
	if hasInitialized {
		out.WriteString("// @ts-expect-error initialized does not accept params.\n")
		out.WriteString("export const rejectInitializedParams = { \"method\": \"initialized\", \"params\": {} } satisfies BoundNotification<\"initialized\">;\n")
	}
	if hasFilesystem {
		out.WriteString("// @ts-expect-error public writes require base64 data.\n")
		out.WriteString("export const rejectFilesystemWriteWithoutData = { path: \"/workspace/file\" } satisfies FsWriteFileParams;\n")
		out.WriteString("// @ts-expect-error copy recursive is non-null when present.\n")
		out.WriteString("export const rejectFilesystemCopyNullRecursive = { sourcePath: \"/workspace/a\", destinationPath: \"/workspace/b\", recursive: null } satisfies FsCopyParams;\n")
		out.WriteString("// @ts-expect-error directory responses require a non-null entries array.\n")
		out.WriteString("export const rejectFilesystemNullEntries = { entries: null } satisfies FsReadDirectoryResponse;\n")
		out.WriteString("// @ts-expect-error watch notifications require changedPaths.\n")
		out.WriteString("export const rejectFilesystemChangedWithoutPaths = { watchId: \"watch\" } satisfies FsChangedNotification;\n")
		out.WriteString("// @ts-expect-error metadata responses require every public field.\n")
		out.WriteString("export const rejectFilesystemPartialMetadata = { isFile: true } satisfies FsGetMetadataResponse;\n")
	}
	return out.Bytes(), nil
}

func typeScriptFixtureEnvelope(fixtureCase typeScriptFixtureCase) (string, error) {
	envelope := fixtureCase.Envelope
	if envelope == "" {
		switch fixtureCase.Surface {
		case SurfaceServerNotification, SurfaceClientNotification:
			envelope = "notification"
		case SurfaceServerRequest, SurfaceClientRequest:
			envelope = "request"
		case SurfaceGollemExtension:
			envelope = "response"
		}
	}

	valid := false
	switch envelope {
	case "notification":
		valid = fixtureCase.Surface == SurfaceServerNotification || fixtureCase.Surface == SurfaceClientNotification
	case "request", "response":
		valid = fixtureCase.Surface == SurfaceClientRequest || fixtureCase.Surface == SurfaceServerRequest || fixtureCase.Surface == SurfaceGollemExtension
	default:
		return "", fmt.Errorf("unsupported envelope %q", envelope)
	}
	if !valid {
		return "", fmt.Errorf("envelope %q is incompatible with surface %q", envelope, fixtureCase.Surface)
	}
	return envelope, nil
}

func typeScriptFixturePayload(message json.RawMessage) (string, error) {
	var envelope struct {
		Params struct {
			Item struct {
				Payload json.RawMessage `json:"payload"`
			} `json:"item"`
		} `json:"params"`
	}
	if err := json.Unmarshal(message, &envelope); err != nil {
		return "", err
	}
	if len(envelope.Params.Item.Payload) == 0 {
		return "", errors.New("params.item.payload is missing")
	}
	var formatted bytes.Buffer
	if err := json.Indent(&formatted, envelope.Params.Item.Payload, "", "  "); err != nil {
		return "", err
	}
	return formatted.String(), nil
}

func typeScriptFixtureBindingExists(fixtureCase typeScriptFixtureCase) bool {
	for _, binding := range WireTypeBindings() {
		if binding.Method != fixtureCase.Method || binding.Surface != fixtureCase.Surface {
			continue
		}
		if fixtureCase.ParamsType != "" && !stringSliceContains(binding.Params, fixtureCase.ParamsType) {
			return false
		}
		if fixtureCase.ResultType != "" && !stringSliceContains(binding.Result, fixtureCase.ResultType) {
			return false
		}
		if fixtureCase.PayloadType != "" {
			for _, payloadBinding := range ItemPayloadBindings() {
				if payloadBinding.Type == fixtureCase.PayloadType {
					return true
				}
			}
			return false
		}
		return true
	}
	return false
}

func stringSliceContains(values []string, want string) bool {
	for _, value := range values {
		if value == want {
			return true
		}
	}
	return false
}

func typeScriptIdentifier(value string) string {
	var out strings.Builder
	upperNext := false
	for i, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upperNext = out.Len() > 0
			continue
		}
		if out.Len() == 0 {
			if unicode.IsDigit(r) {
				out.WriteByte('_')
			}
			out.WriteRune(unicode.ToLower(r))
			continue
		}
		if upperNext {
			r = unicode.ToUpper(r)
			upperNext = false
		} else if i == 0 {
			r = unicode.ToLower(r)
		}
		out.WriteRune(r)
	}
	return out.String()
}
